title = 'kengru'
theme = 'hugo-theme-monochrome'
author = "Kendry Grullon"

baseURL = 'https://kengru.do/'
languageCode = 'en'
defaultContentLanguage = 'en'

googleAnalytics = 'G-KN214PWPJQ'

# Enabling
enableEmoji = true
enable_zooming_js = true

# Theme
[params]
footer = "2023 © Kendry Grullon."
enable_site_search = true

[outputs]
home = ["HTML", "RSS", "JSON"]